#**1. TensorFlow의 기초 문법**
Tensorflow는 텐서 단위로 연산한다      
 





------

###  1) Tensor의 생성 
- tf.constant : 수정 불가한 tensor 생성
- tf.Variable : 수정 가능한 tensor 생성  (assign함수 이용해 특정 위치의 원소를 변경한다)

In [ ]:
# tf.constant : 텐서의 생성(근데 안에 있는 내용은 수정할 수 없다) + numpy와 동일한 기능을 수행할 수 있다
import tensorflow as tf
a = tf.constant([[1,2,3], [4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# 텐서와 numpy array는 유동적으로 변화할 수 있다
import numpy as np
c = np.array([[1,2], [3,4],[5,6]])
print(tf.transpose(c))  # array > tensor로 변환할때는 tf.transpose
print(a.numpy())  # tensor > array로 변환할떄는 numpy()

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int64)
[[1 2 3]
 [4 5 6]]


In [ ]:
print(tf.reduce_mean(a, 0))  
# 하지만 tf.reduce_mean(), tf.reduce_sum(), tf.reduce_max() 등은 numpy와 이름 다름

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [ ]:
a = tf.constant([[1,2,3], [4,5,6]])  
tf.transpose(a)  # tensor를 전치하고 싶을때도 위와 같은 transpose 함수 사용

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
# 3d tensor transpose도 가능
x=tf.constant([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
              [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])  # 3d tensor
print(x.numpy())
tf.transpose(x)  # 3d transpose : 4*3*2 에서 2*3*4가 됨!!

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]], dtype=int32)>

In [ ]:
tf.transpose(x, perm=(0,2,1))  # perm 설정

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]], dtype=int32)>

----------------

### 2) tensorflow에서 data 사용하기 
> numpy 배열이나 list를 **tf.data.Dataset.from_tensor_slices()**를 이용하여 dataset을 생성하고,     iteration을 통해 이를 받아온다

In [ ]:
# tf.data.Dataset.from_tensor_slices()
a=[1.2, 3.4, 7.5, 4.1, 5.0, 1.0, 5.2]
ds = tf.data.Dataset.from_tensor_slices(a)  # dataset 생성
for i in ds:
  print(i.numpy()) # array로 변환하여 출력

1.2
3.4
7.5
4.1
5.0
1.0
5.2


In [ ]:
for i in ds:
  print(i)   # 그냥 출력하면 이렇게된다

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(5.2, shape=(), dtype=float32)


In [ ]:
# 두 tensor를 결합해 데이터로 만들어서 numpy 형태로 출력하기

t_x = tf.random.uniform([4,3], dtype=tf.float32)  # uniform 분포로 4*3 tensor 생성
t_y = tf.range(4)      # shape이 4인 0,1,2,3 들어있는 1차원 tensor 생성

ds_xy = tf.data.Dataset.from_tensor_slices((t_x, t_y))  # 두 텐서들을 dataset으로
for i in ds_xy:
  print(i[0], i[1])
  print(i[0].numpy(), i[1].numpy())
  print('-----------------------------------------------------------------------------------------')

tf.Tensor([0.33740354 0.17238152 0.6156955 ], shape=(3,), dtype=float32) tf.Tensor(0, shape=(), dtype=int32)
[0.33740354 0.17238152 0.6156955 ] 0
-----------------------------------------------------------------------------------------
tf.Tensor([0.6180948  0.19164264 0.5237504 ], shape=(3,), dtype=float32) tf.Tensor(1, shape=(), dtype=int32)
[0.6180948  0.19164264 0.5237504 ] 1
-----------------------------------------------------------------------------------------
tf.Tensor([0.45337605 0.7221775  0.6506742 ], shape=(3,), dtype=float32) tf.Tensor(2, shape=(), dtype=int32)
[0.45337605 0.7221775  0.6506742 ] 2
-----------------------------------------------------------------------------------------
tf.Tensor([0.4604832  0.78395116 0.46727657], shape=(3,), dtype=float32) tf.Tensor(3, shape=(), dtype=int32)
[0.4604832  0.78395116 0.46727657] 3
-----------------------------------------------------------------------------------------


생성된 data를 linear transformation 하고 싶을 때는 **map 함수**를 사용한다 (lambda와 함께!)

In [ ]:
ds_transform = ds_xy.map(lambda x, y : (x*2 - 1, y))  # 2x-1로 transformation
for ex in ds_transform:
  print(ex[0].numpy(), ex[1].numpy())

[-0.32519293 -0.65523696  0.23139095] 0
[ 0.2361896  -0.6167147   0.04750085] 1
[-0.09324789  0.444355    0.30134845] 2
[-0.07903361  0.5679023  -0.06544685] 3


----------------------------
### 3) batch 사용하기
- **.batch()** 함수를 이용한다 (안에는 몇개씩 묶을지 쓰기!)
- drop_remainder=True를 설정하면 남은 애들은 그냥 drop한다



In [ ]:
ds_batch = ds.batch(3, drop_remainder=True)     # 3개씩 묶는다

for i, elem in enumerate(ds_batch, 1):
  print('batch {}'.format(i), elem.numpy())

batch 1 [1.2 3.4 7.5]
batch 2 [4.1 5.  1. ]


In [ ]:
ds_batch   # 다만 이 batch dataset은 tensor도, numpy형도 아니므로 형 변환이 안된다

<BatchDataset shapes: (3,), types: tf.float32>

In [ ]:
ds = ds_xy.batch(3)  # 위에서 정의한 데이터를 3개씩 묶는다(나머지 하나는 떨어져서 나온다!)

for i in ds:
  print(i[0].numpy())  # x 애들
  print(i[1].numpy())  # y 애들
  print('----------------------')

[[0.33740354 0.17238152 0.6156955 ]
 [0.6180948  0.19164264 0.5237504 ]
 [0.45337605 0.7221775  0.6506742 ]]
[0 1 2]
----------------------
[[0.4604832  0.78395116 0.46727657]]
[3]
----------------------


In [ ]:
# batch 내에 repect set 만들기
ds = ds_xy.batch(3).repeat(2)   # 두번 반복되도록 repeat 설계
for i in ds:
  print(i[0].numpy())
  print(i[1].numpy())
  print('-----------------------------------')

[[0.33740354 0.17238152 0.6156955 ]
 [0.6180948  0.19164264 0.5237504 ]
 [0.45337605 0.7221775  0.6506742 ]]
[0 1 2]
-----------------------------------
[[0.4604832  0.78395116 0.46727657]]
[3]
-----------------------------------
[[0.33740354 0.17238152 0.6156955 ]
 [0.6180948  0.19164264 0.5237504 ]
 [0.45337605 0.7221775  0.6506742 ]]
[0 1 2]
-----------------------------------
[[0.4604832  0.78395116 0.46727657]]
[3]
-----------------------------------


In [ ]:
# batch 내에 shuffle 추가
ds = ds_xy.shuffle(4).batch(3).repeat(2)  # 4는 random seed
for i in ds:
  print(i[0].numpy())
  print(i[1].numpy())
  print('-------------------------------------')

[[0.45337605 0.7221775  0.6506742 ]
 [0.33740354 0.17238152 0.6156955 ]
 [0.6180948  0.19164264 0.5237504 ]]
[2 0 1]
-------------------------------------
[[0.4604832  0.78395116 0.46727657]]
[3]
-------------------------------------
[[0.4604832  0.78395116 0.46727657]
 [0.6180948  0.19164264 0.5237504 ]
 [0.45337605 0.7221775  0.6506742 ]]
[3 1 2]
-------------------------------------
[[0.33740354 0.17238152 0.6156955 ]]
[0]
-------------------------------------


-------------------------------

### cf) tensor 자료형은 **type이 일치**되어야만 연산이 가능하다!!
> 불일치 할때는 cast 함수를 사용해 변환해주어야 한다

In [ ]:
t1 = tf.constant(1)
t2 = tf.constant(2.)
tf.cast(t1, tf.float32) + t2 

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
# tf.Variable() : tf.constant와 달리 수정 가능한 tensor를 생성한다. 주로 모수 저장 backend에 쓰인다!
k = tf.Variable([[1,2,3],[4,5,6]])
print(k)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [ ]:
# tf.Variable은 assign() 함수를 이용해 수정할 수 있다
k.assign(k**2) 

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [ ]:
k[0,1].assign(100)  # 이렇게 특정 하나의 위치를 지정해서 변경도 가능하다!

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[  1, 100,   9],
       [ 16,  25,  36]], dtype=int32)>

원소를 동시에 변경하려면 **scatter_nd_update()** 함수를 이용!

In [ ]:
k.scatter_nd_update(indices=[[0,0],[1,0]], updates=[999,999])   # indices는 위치, updates는 새로운 원소 지정

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[999, 100,   9],
       [999,  25,  36]], dtype=int32)>